-- MySQL Script generated by MySQL Workbench
-- Mon Oct 25 12:07:01 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema chess_game
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `chess_game` ;

-- -----------------------------------------------------
-- Schema chess_game
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chess_game` DEFAULT CHARACTER SET latin1 ;
USE `chess_game` ;

-- -----------------------------------------------------
-- Table `chess_game`.`pawnblack`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chess_game`.`pawnblack` (
  `idpawnblack` INT(11) NOT NULL AUTO_INCREMENT,
  `pawn1` CHAR(5) NULL DEFAULT NULL,
  `pawn2` CHAR(5) NULL DEFAULT NULL,
  `pawn3` CHAR(5) NULL DEFAULT NULL,
  `pawn4` CHAR(5) NULL DEFAULT NULL,
  `pawn5` CHAR(5) NULL DEFAULT NULL,
  `pawn6` CHAR(5) NULL DEFAULT NULL,
  `pawn7` CHAR(5) NULL DEFAULT NULL,
  `pawn8` CHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`idpawnblack`))
ENGINE = InnoDB
AUTO_INCREMENT = 644
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `chess_game`.`piecesblack`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chess_game`.`piecesblack` (
  `idpblack` INT(11) NOT NULL AUTO_INCREMENT,
  `towerleft` CHAR(5) NULL DEFAULT NULL,
  `knightleft` CHAR(5) NULL DEFAULT NULL,
  `bishopleft` CHAR(5) NULL DEFAULT NULL,
  `queen` CHAR(5) NULL DEFAULT NULL,
  `king` CHAR(5) NULL DEFAULT NULL,
  `bishopright` CHAR(5) NULL DEFAULT NULL,
  `knightright` CHAR(5) NULL DEFAULT NULL,
  `towerright` CHAR(5) NULL DEFAULT NULL,
  `idpawnblack` INT(11) NOT NULL,
  PRIMARY KEY (`idpblack`),
  CONSTRAINT `FK_idpawnblack_piecesblack`
    FOREIGN KEY (`idpawnblack`)
    REFERENCES `chess_game`.`pawnblack` (`idpawnblack`))
ENGINE = InnoDB
AUTO_INCREMENT = 643
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `FK_idpawnblack_piecesblack` ON `chess_game`.`piecesblack` (`idpawnblack` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `chess_game`.`pawnwhite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chess_game`.`pawnwhite` (
  `idpawnwhite` INT(11) NOT NULL AUTO_INCREMENT,
  `pawn1` CHAR(5) NULL DEFAULT NULL,
  `pawn2` CHAR(5) NULL DEFAULT NULL,
  `pawn3` CHAR(5) NULL DEFAULT NULL,
  `pawn4` CHAR(5) NULL DEFAULT NULL,
  `pawn5` CHAR(5) NULL DEFAULT NULL,
  `pawn6` CHAR(5) NULL DEFAULT NULL,
  `pawn7` CHAR(5) NULL DEFAULT NULL,
  `pawn8` CHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`idpawnwhite`))
ENGINE = InnoDB
AUTO_INCREMENT = 617
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `chess_game`.`pieceswhite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chess_game`.`pieceswhite` (
  `idpwhite` INT(11) NOT NULL AUTO_INCREMENT,
  `towerleft` CHAR(5) NULL DEFAULT NULL,
  `knightleft` CHAR(5) NULL DEFAULT NULL,
  `bishopleft` CHAR(5) NULL DEFAULT NULL,
  `queen` CHAR(5) NULL DEFAULT NULL,
  `king` CHAR(5) NULL DEFAULT NULL,
  `bishopright` CHAR(5) NULL DEFAULT NULL,
  `knightright` CHAR(5) NULL DEFAULT NULL,
  `towerright` CHAR(5) NULL DEFAULT NULL,
  `idpawnwhite` INT(11) NOT NULL,
  PRIMARY KEY (`idpwhite`),
  CONSTRAINT `FK_idpawnwhite_pieceswhite`
    FOREIGN KEY (`idpawnwhite`)
    REFERENCES `chess_game`.`pawnwhite` (`idpawnwhite`))
ENGINE = InnoDB
AUTO_INCREMENT = 609
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `FK_idpawnwhite_pieceswhite` ON `chess_game`.`pieceswhite` (`idpawnwhite` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `chess_game`.`game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chess_game`.`game` (
  `idgame` INT(11) NOT NULL AUTO_INCREMENT,
  `pwhite` INT(11) NULL DEFAULT NULL,
  `pblack` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idgame`),
  CONSTRAINT `FK_pblack_idpawnblack`
    FOREIGN KEY (`pblack`)
    REFERENCES `chess_game`.`piecesblack` (`idpblack`),
  CONSTRAINT `FK_pwhite_idpawnwhite`
    FOREIGN KEY (`pwhite`)
    REFERENCES `chess_game`.`pieceswhite` (`idpwhite`))
ENGINE = InnoDB
AUTO_INCREMENT = 595
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `FK_pwhite_idpawnwhite` ON `chess_game`.`game` (`pwhite` ASC) VISIBLE;

CREATE INDEX `FK_pblack_idpawnblack` ON `chess_game`.`game` (`pblack` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
